{{- /* Header template.
A static file to define BaseClient class that will be
inherited by futures objects and common types.
 */ -}}
{{ define "header" -}}
/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
 {{- if IsBundle }}
import { Context, BaseClient } from "./core.js"
{{- else if (not IsClientOnly)}}
import { Context, BaseClient } from "../common/context.js"
{{- else }}
import { Context, BaseClient, connect as _connect, connection as _connection, ConnectOpts, CallbackFct } from "@dagger.io/dagger"
{{- end }}

{{ if IsClientOnly }}
{{- $mod := BoundModule }}
{{- /* Serve the one module these bindings are bound to before the user's
callback runs, so `dag.<module>()` resolves. The client schema is core + the
bound module only, so there are no dependencies to serve. */}}
async function serveBoundModule(client: Client): Promise<void> {
  {{- if eq $mod.Kind "GIT_SOURCE" }}
  {{- /* A git module's identity is a location that resolves from anywhere:
  serve the canonical ref + pin directly. This survives being shipped away from
  the project tree. */}}
  await client
    .moduleSource("{{ $mod.Ref }}", { refPin: "{{ $mod.Pin }}" })
    .asModule()
    .serve()
  {{- else }}
  {{- /* A local module is resolved against the workspace (discovered by find-up
  from the session cwd — a stable reference point anywhere in the project tree)
  by its workspace-root-relative path, not the client's cwd. */}}
  await client
    .currentWorkspace()
    .moduleSource("{{ $mod.Path }}")
    .asModule()
    .serve()
  {{- end }}
}

export async function connection(
  fct: () => Promise<void>,
  cfg: ConnectOpts = {},
) {
  const wrapperFunc = async (): Promise<void> => {
    await serveBoundModule(dag)

    // Call the callback
    await fct()
  }

  return await _connection(wrapperFunc, cfg)
}

export async function connect(
  fct: CallbackFct,
  cfg: ConnectOpts = {},
) {
  // Serve the bound module before calling the callback
  const wrapperFunc = async (client: Client): Promise<void> => {
    await serveBoundModule(client)

    // Call the callback with the client
    // This requires to use `any` to pass the type system
    await fct(client as any)
  }

  return await _connect(wrapperFunc as unknown as CallbackFct, cfg)
}
{{- end }}

/**
 * Declare a number as float in the Dagger API.
 */
export type float = number

// BaseClient is re-exported so consumers that previously did
// `import { BaseClient } from "./client.gen.js"` keep working. The class
// itself lives in the common SDK runtime (see ../common/context.ts) so that
// per-dependency generated files can extend it without the ESM cycle that
// arises once client.gen.ts `export *`s those dep files.
export { BaseClient }

{{- /* For each dependency: import its types (so inline references like
`new Hello(ctx)` resolve) plus its augmentation function, and re-export
everything so downstream consumers see the dep types via this module. */ -}}
{{- range $dep := DependencyExports }}
import {
  {{ $dep.AugmentFnName }}{{ range $i, $n := $dep.Names }},
  {{ $n }}{{ end }}
} from "./{{ $dep.File }}.gen.js"
export * from "./{{ $dep.File }}.gen.js"
{{- end }}
{{- end }}

{{- /* `footer` runs after all class definitions in client.gen.ts. It calls
each dependency's augmentation function with the now-defined Client / Binding /
Env classes so the dep-contributed prototype methods are attached at module
load time. This is why dep files only ever TYPE-import the extendable classes
from client.gen.ts — avoiding the ESM cycle. */ -}}
{{ define "footer" }}
{{- $deps := DependencyExports }}
{{- if $deps }}
{{- $extendables := ExtendableClassNames }}

// Attach dependency-contributed prototype methods to the extendable classes.
{{- range $dep := $deps }}
{{ $dep.AugmentFnName }}({{ if $extendables }}{ {{ range $i, $c := $extendables }}{{ if $i }}, {{ end }}{{ $c }}{{ end }} }{{ end }})
{{- end }}
{{- end }}
{{- end }}
